title: Jarkko Tervonen
email: jarkko.tervonen@gmail.com
description: Jarkon blogi satunnaisia kirjoituksia koskien webbiä, koodausta, tekniikkaa sekä muita harrastuksia.
baseurl: ""
url: "https://jarkkotervonen.com"
timezone: Europe/Helsinki

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: "/sivu-:num/"
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - deploy.sh
  - deploy.lock
  - todo.md
  - assets/img/posts/orig
