title: Jarkko Tervonen
email: jarkko.tervonen@gmail.com
description: Jarkon blogi satunnaisia kirjoituksia koskien webbiä, koodausta, tekniikkaa sekä muita harrastuksia.
baseurl: ""
url: "https://jarkkotervonen.com"
timezone: Europe/Helsinki

# Build settings
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - deploy.sh
  - deploy.lock
  - todo.md
