title: Jarkko Tervonen
email: jarkko.tervonen@gmail.com
description: Webbiä, koodausta ja muita harrastuksia.
baseurl: ""
url: "http://jarkkotervonen.com"
timezone: Europe/Helsinki

# Build settings
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - deploy.sh
  - deploy.lock
  - todo.md
