defaults: &defaults
  working_directory: ~/blog

version: 2.1
jobs:
  build:
    <<: *defaults

    docker:
      - image: node:alpine
    steps:
      - checkout
      - run:
          name: install utils
          command: apk --no-cache add -U shadow gcc musl-dev autoconf automake make libtool nasm tiff jpeg zlib zlib-dev file pkgconf jpegoptim util-linux python python-dev py-pip build-base
      - run:
          name: update-npm
          command: 'npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  deploy:
    <<: *defaults

    docker:
      - image: circleci/python:2.7.14-stretch

    steps:
      - add_ssh_keys:
          fingerprints:
            - "e7:07:94:0a:c4:02:6d:8a:c5:41:68:86:e8:53:ca:53"

      - attach_workspace:
          at: ./

      - run:
          name: Install rsync
          command: sudo apt install -y rsync

      - run:
          name: Deploy to the server
          command: rsync -v -e "ssh -o StrictHostKeyChecking=no" -r ~/blog/dist/* circleci@field.rcode.fi:/var/www/jarkkotervonen.com/

workflows:
  version: 2.1

  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
